version: "3"
services:
  node: 
    build: .
    # container_name: nodeserver
    ports: 
      - "8080"
    restart: always # 自动重启
    environment: 
      - NODE_ENV=production
    command: npm run start # 覆盖容器启动后默认执行的命令
  nginxweb:
    image: nginx:latest
    ports: 
      - "3000:80"
    container_name: vuenginx
    restart: always
    volumes: 
      - "./nginx:/etc/nginx/conf.d"
      - "./dist:/usr/share/nginx/html"
    links: # 设置 node 服务别名，其实是设置/etc/hosts的域名解析
      - "node"
    depends_on: # 指定依赖于哪个服务
      - node